---
title: "Notes for Novozhilov and Network models"
author: "Richard Zhao"
date: "2025-02-05"
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
output:
  html_document:
    keep_md: true
bibliography: phenHet.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Connection between Novozhilov with network models

-   [Novozhilov(2008)](./refs/Novozhilov2008.pdf)
-   [J.C. Miller, A.C. Slim & E.M. Volz(2011)](./refs/MillerSlimVolz2011.pdf)
-   [I.Z. Kiss, J.C. Miller & P.L. Simon(2017)](./refs/KissMIllerSimon2017Book.pdf)

## Novozhilov's Framework for PhenHet

The Novozhilov framework provide a connection between

-   heterogeneous in susceptibility and/or infectivity with some known distributions parameterized by a single variable (trait) $\omega_s$ or $\omega_i$ and time $t$.
    -   density of susceptible/infected individuals with trait $\omega_s$ or $\omega_i$ is $s(t,\omega_s), i(t, \omega_i)$

    -   pdf $p_s(t,\omega_s)=\frac{s(t,\omega_s)}{S(t)}, p_i(t,\omega_i)=\frac{i(t,\omega_s)}{I(t)}$ respectively

    -   The transmission rate $\beta$ is determined by the traits $\omega_s$ and $\omega_i$ independently, such that $\beta=\beta(\omega_s,\omega_i)=\beta_s(\omega_s) \beta_i(\omega_i)$

    -   For each traits of S, the density $s(t,\omega_s)$ in trait $\omega_s$ is governed by ODE:

        $$\frac{\partial s(t,\omega_s)}{t}=s(t,\omega_s)\beta_s(\omega_s) \int_{\Omega_i} \beta_i(\omega_i) i(t,\omega_i) d \omega_i
        \\
        =s(t,\omega_s)\beta_s(\omega_s)I(t) \int_{\Omega_i} \beta_i(\omega_i) p_i(t,\omega_i) d \omega_i
        \\
        =s(t,\omega_s)\beta_s(\omega_s)I(t) \bar{\beta_i}(t)$$

    -   $\psi(\omega_i,\omega_i')$ is the probability that a newly infected individual gets trait value $\omega_i$ if infected by an individual with trait value $\omega_i'$

        -   Require assumption: the infectivity traits $\omega_i$ of new infected individual must be inherited from its infector, s.t. $$\psi(\omega_i,\omega_i')=\delta(\omega_i'-\omega_i)$$

            with Dirac delta function $\delta(x)$

    -   For each traits of I, the density $i(t,\omega_s)$ in trait $\omega_s$ is governed by ODE:$$
        \frac{\partial i(t,\omega_i)}{t}=\int_{\Omega_s} \int_{\Omega_i} {s(t,\omega_s) \beta_s(\omega_s) \psi(\omega_i,\omega_i') i(t,\omega_i') \beta_i(\omega_i')} d \omega_i' d \omega_s - \gamma i(t,\omega_i)
        \\=\int_{\Omega_s}s(t,\omega_s)\beta_s(\omega_s) d \omega_s \times \int_{\Omega_i}\delta(\omega_i-\omega_i')i(t,\omega_i')\beta_i(\omega_i')d \omega_i'- \gamma i(t,\omega_i)
        \\
        =S(t)\int_{\Omega_s}p_s(t,\omega_s)\beta_s(\omega_s)d \omega_s \times \beta_i(\omega_i)i(t,\omega_i)
        \\
        =S(t) \bar{\beta_s}(t)\beta_i(\omega_i)i(t,\omega_i)- \gamma i(t,\omega_i)
        $$
-   Homogeneous models with general nonlinear but separable transmission functions: $$dS/dt=-h_s(S)\times h_i(I)$$$$dI/dt=h_s(S)\times h_i(I)+\cdots$$
    -   where $h_s$ and $h_i$ are determined purely by the moment generating function (mgf) of $p_s$ and $p_i$ at initial time $t=0$.

A subcase of the general framework, with $\omega_s$ and $\omega_i$ being gamma-distributed and $\beta_s(\omega_s)=\omega_s, \beta_i(\omega_s)=\omega_i \Leftrightarrow \beta=\omega_s\omega_i$ and leads to the known result with power incidence functions $$
\beta S^p I^q
$$at least for SI model.

-   For SIR model, $\beta S^p I$ form has been generated by homogeneous infectivity.

This frame provide a mechanism derivation to a more general class of non-linear incidence expression and provide a clear relationship from the "parametric" heterogeneity to the non-linear incidence term.

However, this framework is limited to following assumptions:

1.  the infectivity traits $\omega_i$ of new infected individual must be inherited from its infector

    -   $\psi(\omega_i,\omega_i')$ is the probability that a newly infected individual gets trait value $\omega_i$ if infected by an individual with trait value $\omega_i'$ and require $\psi(\omega_i,\omega_i')=\delta(\omega_i'-\omega_i)$

    -   This guaranteed that for each infectivity trait $\omega_i$ and time $t$, the population of the infection with such trait satisfy:

        $$
        \frac{\partial s(t,\omega_s)}{t}=-s(t,\omega_s)\times F(S(t),I(t),\omega_i)
        $$$$\frac{\partial i(t,\omega_i)}{t}=i(t,\omega_i)\times G(S(t),I(t),\omega_s)
        $$

        So Theorem 1 in the article could be applied.

    -   This is somehow justifiable if we consider the strain of pathogen or homogeneous in infectivity

2.  The heterogeneity only applies to infectivity and susceptibility while contact rate of individuals are still assumed to be homogeneous and fully-mixed.

3.  The transmission probability/rate $\beta=\beta(\omega_s,\omega_i)$ are determined by traits of infectivity and susceptibility independently s.t. $\beta=\beta(\omega_s,\omega_i)=\beta_s(\omega_s) \beta_i(\omega_i)$

## Network Models with similar settings

Some similar approach using traits and generating functions has been applied to considering heterogeneity in contact rates with networks, by R.M. Anderson, A.L. Lloyd & R.M. May([1988](https://doi.org/10.1098/rstb.1988.0108), [1991 book](https://mcmaster.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma991008325239707371&context=L&vid=01OCUL_MU:OMNI&lang=en&search_scope=OCULDiscoveryNetwork&adaptor=Local%20Search%20Engine&tab=OCULDiscoveryNetwork&query=any,contains,Infectious%20Diseases%20of%20Humans&mode=basic), [2001](https://doi.org/10.1103/PhysRevE.64.066112)) and R. Pastor-Satorras & A. Vespignani ([2001](https://doi.org/10.1103/PhysRevLett.86.3200), [2002](https://doi.org/10.1140/epjb/e20020122)) which release the assumption 2. In these approaches, the traits $\omega$ are replaced by the degree $k$ of the individual/vertex.

-   These network model assume that degree is invariant with time and infection events.
-   Assumption 1, thus the Novozhilov's framework, cannot be applied to network model.

The system of these model can be written into following system by degree $$
\frac{\partial s(t,k)}{\partial t}=-s(t,k) \times k \times \beta \times  \int_{j}\frac{ j P(j) i(t,j)} {\langle K \rangle} dj=-s(t,k) k \beta \int_{j} P_e(j) i(t,j) dj
\\
\frac{\partial i(t,k)}{\partial t}=+s(t,k) \times k \times \beta \times  \int_{j}\frac{ j P(j) i(t,j)} {\langle K \rangle} dj-\gamma i(t,k)
\\=s(t,k) k \beta \int_{j} P_e(j) i(t,j)dj-\gamma i(t,k)
$$

-   $P(k)$ is the degree distribution of the network

-   $s(t,k)$ and $i(t,k)$ are the density of susceptible/infected individual with degree $k$ at time $t$.

-   $\beta$ is the transmission probability of each edge

-   $\langle K \rangle=\int_{k} k P(k)$ is the expected degree

-   $P_e(k)=\frac{k P(k)}{\langle K \rangle}$ is the pdf of excess degree distribution, or the degree-biased distribution

    -   also, the probability of a uniformly randomly chosen edge belongs to a vertex with degree $k$ in the network

    -   also, the probability of a randomly chosen neighbor vertex has degree $k$

    -   Same idea with the size/length-biased sampling: the probability of such neighbor being chosen is proportional to its degree.

-   Comparing with Novozhilov's framework without assumption 1,

    -   $\beta_s(k)=k \beta$ is determined by contact rate/degree of susceptible vertex

    -   $\beta_i(j)=P_e(j)$ is determined by contact rate/degree of the infected vertex

    -   However, $\psi$ is now depend on trait/degree of $s(t,k)$ instead of $i(t,j)$, such that $\psi=\psi(k,k')=\delta(k-k')$

We can find a solution for equation of $s(t,k)$: $$
s(k,t)=e^{-\beta k \int_{-\infty}^{t}P_e(j)i(t',j)dt'}
$$we take $\theta(t)=e^{-\beta \int_{-\infty}^t P_e(j)i(t',j)dt'}$ then $s(k,t)=\theta(t)^k$.

[J.C. Miller, A.C. Slim & E.M. Volz(2011)](./refs/MillerSlimVolz2011.pdf) has proved that with this change of notation, this model is equivalent to their percolation-based model assuming Mean-Field Social Heterogeneity (MFSH) where at each moment, every individual/vertex reform their edges uniformly randomly while keeping their assigned degree and all neighbors are interchangeable in each compartment.

Strong connection with random-network models with assumptions other than MFSH are discussed in [I.Z. Kiss, J.C. Miller & P.L. Simon(2017)](./refs/KissMIllerSimon2017Book.pdf)

Also, Newman & [I.Z. Kiss, J.C. Miller & P.L. Simon(2017)](./refs/KissMIllerSimon2017Book.pdf) has proved that in static/configuration network with large network limit (\$N\$ large enough), the final epidemic size and epidemic threshold of parametric heterogeneous susceptibility ($\tau(x)$) and recovery ($\gamma(x)$) model is the same with homogeneous model with expectation as parameter ($\tau=\langle \tau \rangle, \gamma=\langle \gamma \rangle$).

However, the dynamic will be different and [I.Z. Kiss, J.C. Miller & P.L. Simon(2017)](./refs/KissMIllerSimon2017Book.pdf) has discussion in Chapter 9.
